// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS2JEBB_cJ8pGCfY1vH42RgPCG5k1n3dc',
    appId: '1:1089240369948:web:7ec04a43191e7eeca6c8d9',
    messagingSenderId: '1089240369948',
    projectId: 'first-project-c24fb',
    authDomain: 'first-project-c24fb.firebaseapp.com',
    storageBucket: 'first-project-c24fb.appspot.com',
    measurementId: 'G-KBB659FXNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyaJDQsfqK9PwgmCuWYqE8yvivoo7aXBc',
    appId: '1:1089240369948:android:8691d55a0135c2c9a6c8d9',
    messagingSenderId: '1089240369948',
    projectId: 'first-project-c24fb',
    storageBucket: 'first-project-c24fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs7CICF06HaJOkeThHyhRJWwIAoDV_WPw',
    appId: '1:1089240369948:ios:1f46d2e225136ad7a6c8d9',
    messagingSenderId: '1089240369948',
    projectId: 'first-project-c24fb',
    storageBucket: 'first-project-c24fb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs7CICF06HaJOkeThHyhRJWwIAoDV_WPw',
    appId: '1:1089240369948:ios:1f46d2e225136ad7a6c8d9',
    messagingSenderId: '1089240369948',
    projectId: 'first-project-c24fb',
    storageBucket: 'first-project-c24fb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS2JEBB_cJ8pGCfY1vH42RgPCG5k1n3dc',
    appId: '1:1089240369948:web:7921809a00836b34a6c8d9',
    messagingSenderId: '1089240369948',
    projectId: 'first-project-c24fb',
    authDomain: 'first-project-c24fb.firebaseapp.com',
    storageBucket: 'first-project-c24fb.appspot.com',
    measurementId: 'G-LBTR37W56W',
  );
}
